# Generated by Django 4.2.15 on 2026-09-19 16:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Назва')),
                ('head_of_department', models.CharField(max_length=255, verbose_name='Завідувач кафедри')),
            ],
            options={
                'verbose_name': 'Кафедра',
                'verbose_name_plural': 'Кафедри',
            },
        ),
        migrations.CreateModel(
            name='MainPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Факультет', max_length=200, verbose_name='Заголовок сайту')),
                ('description', models.TextField(verbose_name='Опис факультету')),
                ('main_info', models.TextField(verbose_name='Основна інформація')),
                ('contacts', models.TextField(verbose_name='Контакти')),
            ],
            options={
                'verbose_name': 'Головна сторінка',
                'verbose_name_plural': 'Налаштування головної сторінки',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Імʼя')),
                ('position', models.CharField(max_length=255, verbose_name='Посада')),
                ('degree', models.CharField(max_length=255, verbose_name='Науковий ступінь')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teachers', to='core.department', verbose_name='Кафедра')),
            ],
            options={
                'verbose_name': 'Викладач',
                'verbose_name_plural': 'Викладачі',
            },
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Назва')),
                ('code', models.CharField(max_length=20, verbose_name='Код')),
                ('description', models.TextField(verbose_name='Опис')),
                ('coordinator_name', models.CharField(max_length=255, verbose_name='Імʼя координатора набору')),
                ('coordinator_contact', models.CharField(max_length=255, verbose_name='Контакт координатора')),
                ('subjects', models.TextField(help_text='Вводьте через кому або з нового рядка', verbose_name='Список дисциплін')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programs', to='core.department', verbose_name='Випускова кафедра')),
            ],
            options={
                'verbose_name': 'Спецiальнiсть',
                'verbose_name_plural': 'Спецiальності',
            },
        ),
    ]
