# Generated by Django 4.2.15 on 2026-10-03 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeProgram',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('university', models.CharField(max_length=255, verbose_name='Університет')),
                ('languages', models.CharField(max_length=255, verbose_name='Мови навчання')),
                ('places', models.CharField(max_length=100, verbose_name='Кількість місць')),
                ('deadline', models.DateField(verbose_name='Дедлайн подачі')),
                ('description', models.TextField(verbose_name='Опис')),
            ],
            options={
                'verbose_name': 'Програма обміну',
                'verbose_name_plural': 'Програми обміну',
            },
        ),
    ]
