# Generated by Django 4.2.15 on 2026-10-03 16:34

from django.db import migrations


def get_insert_sql():
    return """
    INSERT INTO core_exchangeprogram (university, languages, places, deadline, description)
    VALUES 
    ('Uniwersytet Warszawski, Польща', 'польська, англійська', '5', '2026-11-15', 'Партнерська програма з Варшавським університетом для здобувачів вищої освіти.'),
    ('KU Leuven (Бельгія)', 'English', '2 місця', '2026-12-01', 'Програма семестрового обміну в одному з найстаріших університетів Європи.'),
    ('Vilnius University, Литва', 'англійська', 'до 4', '2026-10-20', 'Академічна мобільність у Вільнюському університеті для студентів бакалавріату.'),
    ('Uniwersytet Jagielloński, Польща', 'Польська, Англійська', '3', '2026-11-15', 'Навчання протягом семестру в Ягеллонському університеті в Кракові.'),
    ('University of Tartu - Естонія', 'англійська, естонська', '2', '2027-01-10', 'Програма академічного обміну в провідному закладі вищої освіти Естонії.'),
    ('Masaryk University, Чехія', 'англійська', '1 місце', '2026-09-30', 'Семестрове навчання в Масариковому університеті в місті Брно.');
    """


def get_reverse_sql():
    return """
    DELETE FROM core_exchangeprogram 
    WHERE university IN (
        'Uniwersytet Warszawski, Польща',
        'KU Leuven (Бельгія)',
        'Vilnius University, Литва',
        'Uniwersytet Jagielloński, Польща',
        'University of Tartu - Естонія',
        'Masaryk University, Чехія'
    );
    """


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_create_exchangeprogram'),
    ]

    operations = [
        migrations.RunSQL(
            sql=get_insert_sql(),
            reverse_sql=get_reverse_sql()
        )
    ]
