# Generated by Django 4.2.15 on 2026-10-03 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_seed_exchange_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchangeprogram',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Країна'),
        ),
        migrations.AddField(
            model_name='exchangeprogram',
            name='university_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Назва університету'),
        ),
    ]
