# Generated by Django 4.2.15 on 2026-10-03 16:40

from django.db import migrations
import re


def split_university_data(apps, schema_editor):
    ExchangeProgram = apps.get_model('core', 'ExchangeProgram')
    for program in ExchangeProgram.objects.all():
        if not program.university:
            continue
        raw = program.university.strip()
        if ',' in raw:
            parts = raw.split(',', 1)
            program.university_name = parts[0].strip()
            program.country = parts[1].strip()
        elif ' - ' in raw:
            parts = raw.split(' - ', 1)
            program.university_name = parts[0].strip()
            program.country = parts[1].strip()
        elif '(' in raw and ')' in raw:
            match = re.search(r'^(.*?)\s*\((.*?)\)$', raw)
            if match:
                program.university_name = match.group(1).strip()
                program.country = match.group(2).strip()
        else:
            program.university_name = raw
            program.country = "Невідомо"
        program.save()


def reverse_split_university_data(apps, schema_editor):
    ExchangeProgram = apps.get_model('core', 'ExchangeProgram')
    for program in ExchangeProgram.objects.all():
        if program.university_name and program.country:
            program.university = f"{program.university_name}, {program.country}"
            program.save()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_add_university_name_and_country'),
    ]

    operations = [
        migrations.RunPython(split_university_data, reverse_code=reverse_split_university_data)
    ]
