# Generated by Django 4.2.15 on 2026-10-03 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_separate_university_and_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchangeprogram',
            name='places_count',
            field=models.IntegerField(blank=True, null=True, verbose_name='Кількість місць'),
        ),
        migrations.AlterField(
            model_name='exchangeprogram',
            name='places',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Кількість місць (старе)'),
        ),
    ]
