# Generated by Django 4.2.15 on 2026-10-03 16:46

from django.db import migrations
import re


def convert_places_to_number(apps, schema_editor):
    ExchangeProgram = apps.get_model('core', 'ExchangeProgram')
    for program in ExchangeProgram.objects.all():
        if not program.places:
            continue
        numbers = re.findall(r'\d+', program.places)
        if numbers:
            program.places_count = int(numbers[0])
        else:
            program.places_count = 0
        program.save()


def reverse_convert_places(apps, schema_editor):
    ExchangeProgram = apps.get_model('core', 'ExchangeProgram')
    for program in ExchangeProgram.objects.all():
        if program.places_count is not None:
            program.places = str(program.places_count)
            program.save()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_add_places_count'),
    ]

    operations = [
        migrations.RunPython(convert_places_to_number, reverse_code=reverse_convert_places)
    ]
